# Generated by Django 5.1.4 on 2025-01-14 00:24

import core.helpers.dates
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.TextField(max_length=150, verbose_name='name')),
                ('name_en', models.TextField(max_length=150, verbose_name='name')),
                ('short_description_ru', models.TextField(blank=True, max_length=256, verbose_name='short description')),
                ('short_description_en', models.TextField(blank=True, max_length=256, verbose_name='short description')),
                ('description_ru', models.TextField(blank=True, max_length=1024, verbose_name='description')),
                ('description_en', models.TextField(blank=True, max_length=1024, verbose_name='description')),
                ('portrait_picture', models.ImageField(blank=True, upload_to='authors', verbose_name='portrait picture')),
                ('promote', models.BooleanField(default=False, help_text='Promote on the main page', verbose_name='promote')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(max_length=150, verbose_name='text')),
                ('text_en', models.TextField(max_length=150, verbose_name='text')),
                ('promote', models.BooleanField(default=False, help_text='Promote on the main page', verbose_name='promote')),
            ],
            options={
                'verbose_name': 'rubric',
                'verbose_name_plural': 'rubrics',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(max_length=150, verbose_name='text')),
                ('text_en', models.TextField(max_length=150, verbose_name='text')),
                ('promote', models.BooleanField(default=False, help_text='Promote on the main page', verbose_name='promote')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('address', models.TextField(blank=True, default='', verbose_name='addrress')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.TextField(choices=[('ACADEMIC', 'Academic'), ('NORMAL', 'Normal'), ('HONORARY', 'Honorary')], default='NORMAL')),
                ('started', models.IntegerField(default=core.helpers.dates.this_year)),
                ('until', models.IntegerField(default=core.helpers.dates.this_year)),
                ('mailing_list', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.TextField(help_text='The track title text, required.', max_length=150, verbose_name='title')),
                ('title_en', models.TextField(help_text='The track title text, required.', max_length=150, verbose_name='title')),
                ('description_ru', models.TextField(blank=True, help_text='Optional description', max_length=512, verbose_name='description')),
                ('description_en', models.TextField(blank=True, help_text='Optional description', max_length=512, verbose_name='description')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video link url', max_length=150, verbose_name='youtube link')),
                ('audio_file', models.FileField(upload_to='tracks/%Y-%m-%d', verbose_name='Audio file')),
                ('preview_picture', models.ImageField(blank=True, upload_to='tracks/%Y-%m-%d', verbose_name='Preview picture')),
                ('track_status', models.TextField(choices=[('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden'), ('TEST', 'Test')], default='PUBLISHED', verbose_name='status')),
                ('for_members', models.BooleanField(default=False, verbose_name='for members only')),
                ('played_count', models.BigIntegerField(blank=True, default=0, help_text='Played count')),
                ('audio_duration', models.BigIntegerField(help_text='Duration (seconds)', null=True)),
                ('audio_size', models.BigIntegerField(help_text='File size (bytes)', null=True)),
                ('published_at', models.DateField(default=datetime.date.today, verbose_name='published at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tales_django.author', verbose_name='author')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='publisher', to=settings.AUTH_USER_MODEL, verbose_name='published by')),
                ('rubrics', models.ManyToManyField(blank=True, related_name='rubricated_tracks', to='tales_django.rubric', verbose_name='rubrics')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_tracks', to='tales_django.tag', verbose_name='tags')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updater', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'track',
                'verbose_name_plural': 'tracks',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='tales_django.track'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='tales_django.track'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_tracks',
            field=models.ManyToManyField(blank=True, related_name='favorited_users', to='tales_django.track', verbose_name='favorite tracks'),
        ),
        migrations.AddField(
            model_name='user',
            name='playlist_tracks',
            field=models.ManyToManyField(blank=True, related_name='playlisted_users', to='tales_django.track', verbose_name='playlist'),
        ),
    ]
