# Generated by Django 5.0 on 2025-02-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_duration',
            field=models.FloatField(help_text='Duration (seconds)', null=True),
        ),
    ]
