# Generated by Django 5.0 on 2025-03-13 18:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0003_alter_author_name_en_alter_author_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Rubric', 'verbose_name_plural': 'Rubrics'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AlterField(
            model_name='author',
            name='description_en',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description_ru',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_en',
            field=models.TextField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_ru',
            field=models.TextField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='portrait_picture',
            field=models.ImageField(blank=True, upload_to='authors', verbose_name='Portrait picture'),
        ),
        migrations.AlterField(
            model_name='author',
            name='promote',
            field=models.BooleanField(default=False, help_text='Promote on the main page', verbose_name='Promote'),
        ),
        migrations.AlterField(
            model_name='author',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=512, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='short_description_ru',
            field=models.TextField(blank=True, max_length=512, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='promote',
            field=models.BooleanField(default=False, help_text='Promote on the main page', verbose_name='Promote'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='text_en',
            field=models.TextField(max_length=256, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='text_ru',
            field=models.TextField(max_length=256, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='promote',
            field=models.BooleanField(default=False, help_text='Promote on the main page', verbose_name='Promote'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text_en',
            field=models.TextField(max_length=256, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text_ru',
            field=models.TextField(max_length=256, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tales_django.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description_en',
            field=models.TextField(blank=True, help_text='Optional description', max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Optional description', max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='track',
            name='for_members',
            field=models.BooleanField(default=False, verbose_name='For members only'),
        ),
        migrations.AlterField(
            model_name='track',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Published at'),
        ),
        migrations.AlterField(
            model_name='track',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='publisher', to=settings.AUTH_USER_MODEL, verbose_name='Published by'),
        ),
        migrations.AlterField(
            model_name='track',
            name='rubrics',
            field=models.ManyToManyField(blank=True, related_name='rubricated_tracks', to='tales_django.rubric', verbose_name='Rubrics'),
        ),
        migrations.AlterField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_tracks', to='tales_django.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title_en',
            field=models.TextField(help_text='The track title text, required.', max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title_ru',
            field=models.TextField(help_text='The track title text, required.', max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_status',
            field=models.TextField(choices=[('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden'), ('TEST', 'Test')], default='PUBLISHED', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='track',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='track',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updater', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='track',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video link url', max_length=64, verbose_name='Youtube link'),
        ),
    ]
