# Generated by Django 5.0 on 2025-03-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0004_alter_author_options_alter_rubric_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='played_count',
            field=models.BigIntegerField(blank=True, default=0, help_text='Played count', verbose_name='Played count'),
        ),
        migrations.AlterField(
            model_name='track',
            name='preview_picture',
            field=models.ImageField(upload_to='tracks/%Y-%m-%d', verbose_name='Preview picture'),
        ),
    ]
