# Generated by Django 5.0 on 2025-03-14 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0005_alter_track_played_count_alter_track_preview_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tales_django.author', verbose_name='Author'),
            preserve_default=False,
        ),
    ]
