# Generated by Django 5.0 on 2025-03-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0006_alter_track_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='portrait_picture',
            field=models.ImageField(upload_to='authors', verbose_name='Portrait picture'),
        ),
    ]
