# Generated by Django 5.0 on 2025-03-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0007_alter_author_portrait_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='promote',
            field=models.BooleanField(default=False, help_text='Promote on the main page', verbose_name='Promote'),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_notifications',
            field=models.BooleanField(default=False, help_text='Receive notifications via email and in the mobile application', verbose_name='Allow notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Addrress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_tracks',
            field=models.ManyToManyField(blank=True, related_name='favorited_users', to='tales_django.track', verbose_name='Favorite tracks'),
        ),
        migrations.AlterField(
            model_name='user',
            name='playlist_tracks',
            field=models.ManyToManyField(blank=True, related_name='playlisted_users', to='tales_django.track', verbose_name='Playlist'),
        ),
    ]
