# Generated by Django 5.0 on 2025-03-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0008_track_promote_user_allow_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='for_members',
            field=models.BooleanField(default=False, help_text='Show only for privileged members', verbose_name='For members only'),
        ),
    ]
