# Generated by Django 5.0 on 2025-03-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0009_alter_track_for_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='played_count',
            field=models.BigIntegerField(blank=True, default=0, help_text='Played count'),
        ),
    ]
