# Generated by Django 5.0 on 2025-03-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0010_alter_track_played_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_duration',
            field=models.FloatField(null=True, verbose_name='Duration (seconds)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_size',
            field=models.BigIntegerField(null=True, verbose_name='File size (bytes)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='played_count',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Played count'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_status',
            field=models.TextField(choices=[('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden'), ('TEST', 'Test')], default='PUBLISHED', help_text='Only published tracks will be shown', verbose_name='Status'),
        ),
    ]
