# Generated by Django 5.0 on 2025-04-03 05:22

import django.contrib.auth.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('flatpages', '0001_initial'),
        ('tales_django', '0012_alter_author_promote_alter_rubric_promote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('page_title_ru', models.CharField(default='', max_length=200, verbose_name='page_title')),
                ('page_title_en', models.CharField(default='', max_length=200, verbose_name='page_title')),
                ('page_content_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='page_content')),
                ('page_content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='page_content')),
            ],
            options={
                'verbose_name': 'Flat page',
                'verbose_name_plural': 'Flat pages',
                'db_table': 'tales_django_flatpage',
            },
            bases=('flatpages.flatpage',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
