# Generated by Django 5.0 on 2025-04-03 12:43

import datetime
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0013_flatpage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Published at'),
        ),
        migrations.AddField(
            model_name='author',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Published at'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Published at'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='tag',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Published at'),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_en',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_ru',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='page_content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Page content'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='page_content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Page content'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='page_title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Page title'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='page_title_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Page title'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='text_en',
            field=models.CharField(max_length=256, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='text_ru',
            field=models.CharField(max_length=256, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text_en',
            field=models.CharField(max_length=256, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text_ru',
            field=models.CharField(max_length=256, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title_en',
            field=models.CharField(help_text='The track title text, required.', max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title_ru',
            field=models.CharField(help_text='The track title text, required.', max_length=256, verbose_name='Title'),
        ),
    ]
