# Generated by Django 5.0 on 2025-04-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0013_flatpage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='content_en',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='content_ru',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='title_ru',
            field=models.CharField(default='', max_length=200, verbose_name='title'),
        ),
    ]
