# Generated by Django 5.0 on 2025-05-02 14:31

import datetime
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0015_alter_track_played_count_usertrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STRING', 'string'), ('BLOCK', 'block'), ('RICH_BLOCK', 'rich block')], default='STRING', max_length=16)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='content')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='content')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'content block',
                'verbose_name_plural': 'content blocks',
            },
        ),
    ]
