# Generated by Django 5.0 on 2025-05-02 15:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0016_contentblocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblocks',
            name='active',
            field=models.BooleanField(default=True, help_text='Use this value', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='contentblocks',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='contentblocks',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='contentblocks',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contentblocks',
            name='type',
            field=models.CharField(choices=[('STRING', 'String'), ('BLOCK', 'Block'), ('RICH_BLOCK', 'Rich block')], default='STRING', max_length=16, verbose_name='Type'),
        ),
    ]
