# Generated by Django 5.0 on 2026-01-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0017_contentblocks_active_alter_contentblocks_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='series_order',
            field=models.PositiveIntegerField(default=1, help_text='Order within the series (lower numbers appear first)', verbose_name='Order in Series'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(help_text='The series title text, required.', max_length=256, verbose_name='Title')),
                ('title_en', models.CharField(help_text='The series title text, required.', max_length=256, verbose_name='Title')),
                ('description_ru', models.TextField(blank=True, help_text='Optional series description', max_length=1024, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, help_text='Optional series description', max_length=1024, verbose_name='Description')),
                ('promote', models.BooleanField(default=True, help_text='Promote on the main page', verbose_name='Promote')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this series is visible to users', verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tracks', models.ManyToManyField(blank=True, related_name='series_tracks', to='tales_django.track')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='serialized_tracks', to='tales_django.series', verbose_name='Series'),
        ),
    ]
