# Generated by Django 5.0 on 2026-01-27 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0017_contentblocks_active_alter_contentblocks_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(help_text='The series title text, required.', max_length=256, verbose_name='Title')),
                ('title_en', models.CharField(help_text='The series title text, required.', max_length=256, verbose_name='Title')),
                ('description_ru', models.TextField(blank=True, help_text='Optional series description', max_length=1024, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, help_text='Optional series description', max_length=1024, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Series display order (lower numbers appear first)', verbose_name='Order')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this series is visible to users', verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='track',
            name='series_order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the series (lower numbers appear first)', verbose_name='Series Order'),
        ),
        migrations.AddField(
            model_name='track',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Optional series this track belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='tales_django.series', verbose_name='Series'),
        ),
    ]
