# Generated by Django 5.0 on 2026-01-29 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0018_series_track_series_order_track_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series (plural)'},
        ),
    ]
