# Generated by Django 5.0 on 2026-01-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0018_add_series_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.RemoveField(
            model_name='series',
            name='order',
        ),
    ]
