# Generated by Django 5.0 on 2026-01-27 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0019_remove_series_order_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='series_order',
        ),
        migrations.CreateModel(
            name='TrackSeriesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the series (lower numbers appear first)', verbose_name='Order in Series')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tales_django.series')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tales_django.track')),
            ],
            options={
                'ordering': ['series', 'order'],
                'unique_together': {('series', 'order')},
            },
        ),
    ]
