# Generated by Django 5.0 on 2026-01-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0020_remove_track_series_order_trackseriesorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='series',
        ),
        migrations.AddField(
            model_name='series',
            name='tracks',
            field=models.ManyToManyField(related_name='series', through='tales_django.TrackSeriesOrder', to='tales_django.track', verbose_name='Tracks'),
        ),
    ]
