# Generated by Django 5.0 on 2026-01-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales_django', '0021_remove_track_series_series_tracks'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trackseriesorder',
            index=models.Index(fields=['track'], name='tales_djang_track_i_7e3ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='trackseriesorder',
            index=models.Index(fields=['series'], name='tales_djang_series__da2279_idx'),
        ),
        migrations.AddIndex(
            model_name='trackseriesorder',
            index=models.Index(fields=['order'], name='tales_djang_order_c569d3_idx'),
        ),
    ]
